/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javastockmanagementapp;

import javastockmanagementapp.Interfaces.Stock;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anuj
 */
public class frmStockManagement extends javax.swing.JFrame implements Stock {

    /**
     * Creates new form frmStockManagement
     */
    public frmStockManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStockVisual = new javax.swing.JTable(){
            private static final long serialVersionUID = 1L;
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return Integer.class;
                    default:
                    return String.class;
                }
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlaceOrder = new javax.swing.JTable(){
            private static final long serialVersionUID = 1L;
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return Boolean.class;
                    case 1:
                    return String.class;
                    case 2:
                    return Integer.class;
                    default:
                    return String.class;
                }
            }

        };
        btnPlaceOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(tblStockVisual);

        jScrollPane2.setViewportView(tblPlaceOrder);

        btnPlaceOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Place Order");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Current Stock Visualisation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(54, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        java.sql.Timestamp date = new java.sql.Timestamp(new java.util.Date().getTime());
        getProductsToOrder(tblPlaceOrder).entrySet().forEach((_item) -> {
            try {
                PreparedStatement psInsertOrder = dbConnect.getConnection().
                        prepareStatement("Insert into tblstockorders values (?,?,?)");
                psInsertOrder.setString(1,getProduct(_item.getKey()).pdtRefNum);
                psInsertOrder.setInt(2, _item.getValue());
                psInsertOrder.setTimestamp(3, date);
                psInsertOrder.execute();
                JOptionPane.showMessageDialog(null, "Order Placed Successfully");
            } catch (SQLException ex) {
                Logger.getLogger(frmStockManagement.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(frmStockManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                frmStockManagement objStockManagement = new frmStockManagement();
                objStockManagement.setVisible(true);
                objStockManagement.updateTable(tblStockVisual);
                objStockManagement.fillTable(tblPlaceOrder);
            } catch (Exception ex) {
                Logger.getLogger(frmStockManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    
    //Update stock visualisation table
    @Override
    public void updateTable(JTable tbl) {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Product Name", "Quantity"});
        try {
            ResultSet result = dbConnect.getConnection().createStatement().
                    executeQuery("SELECT p.pdtName, s.Quantity "
                            +    "FROM tblstock s, tblproducts p "
                            +    "WHERE p.pdtID = s.pdtID; ");

            while (result.next()) {
                model.addRow(new Object[]{result.getString("pdtName"),
                    result.getFloat("Quantity")});
            }
        } catch (Exception ex) {
            try {
                throw ex;
            } catch (Exception ex1) {
                Logger.getLogger(frmStockManagement.class.getName()).log(Level.SEVERE, null, ex1);
            }
        } finally {
            tbl.setModel(model);
        }
    }
    
    //display Items in Order Table
    @Override
    public void fillTable(javax.swing.JTable tbl){
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"","Product Name", "Enter Quantity"});
        try {
            ResultSet result = dbConnect.getConnection().createStatement().
                    executeQuery("SELECT p.pdtName "
                            +    "FROM tblstock s, tblproducts p "
                            +    "WHERE p.pdtID = s.pdtID; ");

            while (result.next()) {
                model.addRow(new Object[]{false,result.getString("pdtName"),
                    null});
            }
        } catch (Exception ex) {
            try {
                throw ex;
            } catch (Exception ex1) {
                Logger.getLogger(frmStockManagement.class.getName()).log(Level.SEVERE, null, ex1);
            }
        } finally {
             tbl.setModel(model);
        }
    }
    
    //get selected products and respective quantities to order
     @Override
    public HashMap<String, Integer> getProductsToOrder(javax.swing.JTable tbl){
        HashMap<String, Integer> productsToOrder = new HashMap<>();
         for(int i = 0;i<tbl.getRowCount();i++){
            if(tbl.getValueAt(i, 0) == Boolean.TRUE){
                productsToOrder.put((String) tbl.getValueAt(i, 1),(Integer) tbl.getValueAt(i, 2));
            }
        }
        return productsToOrder;
    }
    
    //get product reference number given its name
     @Override
    public clsProduct getProduct(String pdtName){
        try {
            PreparedStatement psGetClient = dbConnect.getConnection().
                    prepareStatement("Select * from tblproducts where pdtName=?");
            psGetClient.setString(1,pdtName);
            ResultSet result = psGetClient.executeQuery();
            result.next();
            return new clsProduct(result.getString("pdtID"),
                    result.getString("pdtName"),
                    result.getString("pdtRefNum"),
                    result.getFloat("pdtUnitPrice"));
        } catch (Exception ex) {
            Logger.getLogger(frmStockManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable tblPlaceOrder;
    private static javax.swing.JTable tblStockVisual;
    // End of variables declaration//GEN-END:variables
}
